// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stackitcloud/stackit-sdk-go/services/ske/v2api (interfaces: DefaultAPI)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/mock/ske/ske.go -package ske github.com/stackitcloud/stackit-sdk-go/services/ske/v2api DefaultAPI
//

// Package ske is a generated GoMock package.
package ske

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/ske/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultAPI is a mock of DefaultAPI interface.
type MockDefaultAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultAPIMockRecorder
	isgomock struct{}
}

// MockDefaultAPIMockRecorder is the mock recorder for MockDefaultAPI.
type MockDefaultAPIMockRecorder struct {
	mock *MockDefaultAPI
}

// NewMockDefaultAPI creates a new mock instance.
func NewMockDefaultAPI(ctrl *gomock.Controller) *MockDefaultAPI {
	mock := &MockDefaultAPI{ctrl: ctrl}
	mock.recorder = &MockDefaultAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultAPI) EXPECT() *MockDefaultAPIMockRecorder {
	return m.recorder
}

// CompleteCredentialsRotation mocks base method.
func (m *MockDefaultAPI) CompleteCredentialsRotation(ctx context.Context, projectId, region, clusterName string) v2api.ApiCompleteCredentialsRotationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCredentialsRotation", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiCompleteCredentialsRotationRequest)
	return ret0
}

// CompleteCredentialsRotation indicates an expected call of CompleteCredentialsRotation.
func (mr *MockDefaultAPIMockRecorder) CompleteCredentialsRotation(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCredentialsRotation", reflect.TypeOf((*MockDefaultAPI)(nil).CompleteCredentialsRotation), ctx, projectId, region, clusterName)
}

// CompleteCredentialsRotationExecute mocks base method.
func (m *MockDefaultAPI) CompleteCredentialsRotationExecute(r v2api.ApiCompleteCredentialsRotationRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCredentialsRotationExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteCredentialsRotationExecute indicates an expected call of CompleteCredentialsRotationExecute.
func (mr *MockDefaultAPIMockRecorder) CompleteCredentialsRotationExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCredentialsRotationExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CompleteCredentialsRotationExecute), r)
}

// CreateKubeconfig mocks base method.
func (m *MockDefaultAPI) CreateKubeconfig(ctx context.Context, projectId, region, clusterName string) v2api.ApiCreateKubeconfigRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubeconfig", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiCreateKubeconfigRequest)
	return ret0
}

// CreateKubeconfig indicates an expected call of CreateKubeconfig.
func (mr *MockDefaultAPIMockRecorder) CreateKubeconfig(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubeconfig", reflect.TypeOf((*MockDefaultAPI)(nil).CreateKubeconfig), ctx, projectId, region, clusterName)
}

// CreateKubeconfigExecute mocks base method.
func (m *MockDefaultAPI) CreateKubeconfigExecute(r v2api.ApiCreateKubeconfigRequest) (*v2api.Kubeconfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubeconfigExecute", r)
	ret0, _ := ret[0].(*v2api.Kubeconfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKubeconfigExecute indicates an expected call of CreateKubeconfigExecute.
func (mr *MockDefaultAPIMockRecorder) CreateKubeconfigExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubeconfigExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateKubeconfigExecute), r)
}

// CreateOrUpdateCluster mocks base method.
func (m *MockDefaultAPI) CreateOrUpdateCluster(ctx context.Context, projectId, region, clusterName string) v2api.ApiCreateOrUpdateClusterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateCluster", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiCreateOrUpdateClusterRequest)
	return ret0
}

// CreateOrUpdateCluster indicates an expected call of CreateOrUpdateCluster.
func (mr *MockDefaultAPIMockRecorder) CreateOrUpdateCluster(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateCluster", reflect.TypeOf((*MockDefaultAPI)(nil).CreateOrUpdateCluster), ctx, projectId, region, clusterName)
}

// CreateOrUpdateClusterExecute mocks base method.
func (m *MockDefaultAPI) CreateOrUpdateClusterExecute(r v2api.ApiCreateOrUpdateClusterRequest) (*v2api.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateClusterExecute", r)
	ret0, _ := ret[0].(*v2api.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateClusterExecute indicates an expected call of CreateOrUpdateClusterExecute.
func (mr *MockDefaultAPIMockRecorder) CreateOrUpdateClusterExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateClusterExecute", reflect.TypeOf((*MockDefaultAPI)(nil).CreateOrUpdateClusterExecute), r)
}

// DeleteCluster mocks base method.
func (m *MockDefaultAPI) DeleteCluster(ctx context.Context, projectId, region, clusterName string) v2api.ApiDeleteClusterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiDeleteClusterRequest)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockDefaultAPIMockRecorder) DeleteCluster(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteCluster), ctx, projectId, region, clusterName)
}

// DeleteClusterExecute mocks base method.
func (m *MockDefaultAPI) DeleteClusterExecute(r v2api.ApiDeleteClusterRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClusterExecute indicates an expected call of DeleteClusterExecute.
func (mr *MockDefaultAPIMockRecorder) DeleteClusterExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterExecute", reflect.TypeOf((*MockDefaultAPI)(nil).DeleteClusterExecute), r)
}

// GetCluster mocks base method.
func (m *MockDefaultAPI) GetCluster(ctx context.Context, projectId, region, clusterName string) v2api.ApiGetClusterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiGetClusterRequest)
	return ret0
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockDefaultAPIMockRecorder) GetCluster(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockDefaultAPI)(nil).GetCluster), ctx, projectId, region, clusterName)
}

// GetClusterExecute mocks base method.
func (m *MockDefaultAPI) GetClusterExecute(r v2api.ApiGetClusterRequest) (*v2api.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterExecute", r)
	ret0, _ := ret[0].(*v2api.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterExecute indicates an expected call of GetClusterExecute.
func (mr *MockDefaultAPIMockRecorder) GetClusterExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetClusterExecute), r)
}

// GetIDPKubeconfig mocks base method.
func (m *MockDefaultAPI) GetIDPKubeconfig(ctx context.Context, projectId, region, clusterName string) v2api.ApiGetIDPKubeconfigRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPKubeconfig", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiGetIDPKubeconfigRequest)
	return ret0
}

// GetIDPKubeconfig indicates an expected call of GetIDPKubeconfig.
func (mr *MockDefaultAPIMockRecorder) GetIDPKubeconfig(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPKubeconfig", reflect.TypeOf((*MockDefaultAPI)(nil).GetIDPKubeconfig), ctx, projectId, region, clusterName)
}

// GetIDPKubeconfigExecute mocks base method.
func (m *MockDefaultAPI) GetIDPKubeconfigExecute(r v2api.ApiGetIDPKubeconfigRequest) (*v2api.IDPKubeconfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPKubeconfigExecute", r)
	ret0, _ := ret[0].(*v2api.IDPKubeconfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDPKubeconfigExecute indicates an expected call of GetIDPKubeconfigExecute.
func (mr *MockDefaultAPIMockRecorder) GetIDPKubeconfigExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPKubeconfigExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetIDPKubeconfigExecute), r)
}

// GetLoginKubeconfig mocks base method.
func (m *MockDefaultAPI) GetLoginKubeconfig(ctx context.Context, projectId, region, clusterName string) v2api.ApiGetLoginKubeconfigRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginKubeconfig", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiGetLoginKubeconfigRequest)
	return ret0
}

// GetLoginKubeconfig indicates an expected call of GetLoginKubeconfig.
func (mr *MockDefaultAPIMockRecorder) GetLoginKubeconfig(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginKubeconfig", reflect.TypeOf((*MockDefaultAPI)(nil).GetLoginKubeconfig), ctx, projectId, region, clusterName)
}

// GetLoginKubeconfigExecute mocks base method.
func (m *MockDefaultAPI) GetLoginKubeconfigExecute(r v2api.ApiGetLoginKubeconfigRequest) (*v2api.LoginKubeconfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginKubeconfigExecute", r)
	ret0, _ := ret[0].(*v2api.LoginKubeconfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginKubeconfigExecute indicates an expected call of GetLoginKubeconfigExecute.
func (mr *MockDefaultAPIMockRecorder) GetLoginKubeconfigExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginKubeconfigExecute", reflect.TypeOf((*MockDefaultAPI)(nil).GetLoginKubeconfigExecute), r)
}

// ListClusters mocks base method.
func (m *MockDefaultAPI) ListClusters(ctx context.Context, projectId, region string) v2api.ApiListClustersRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx, projectId, region)
	ret0, _ := ret[0].(v2api.ApiListClustersRequest)
	return ret0
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockDefaultAPIMockRecorder) ListClusters(ctx, projectId, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockDefaultAPI)(nil).ListClusters), ctx, projectId, region)
}

// ListClustersExecute mocks base method.
func (m *MockDefaultAPI) ListClustersExecute(r v2api.ApiListClustersRequest) (*v2api.ListClustersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClustersExecute", r)
	ret0, _ := ret[0].(*v2api.ListClustersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersExecute indicates an expected call of ListClustersExecute.
func (mr *MockDefaultAPIMockRecorder) ListClustersExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListClustersExecute), r)
}

// ListProviderOptions mocks base method.
func (m *MockDefaultAPI) ListProviderOptions(ctx context.Context, region string) v2api.ApiListProviderOptionsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviderOptions", ctx, region)
	ret0, _ := ret[0].(v2api.ApiListProviderOptionsRequest)
	return ret0
}

// ListProviderOptions indicates an expected call of ListProviderOptions.
func (mr *MockDefaultAPIMockRecorder) ListProviderOptions(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviderOptions", reflect.TypeOf((*MockDefaultAPI)(nil).ListProviderOptions), ctx, region)
}

// ListProviderOptionsExecute mocks base method.
func (m *MockDefaultAPI) ListProviderOptionsExecute(r v2api.ApiListProviderOptionsRequest) (*v2api.ProviderOptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviderOptionsExecute", r)
	ret0, _ := ret[0].(*v2api.ProviderOptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviderOptionsExecute indicates an expected call of ListProviderOptionsExecute.
func (mr *MockDefaultAPIMockRecorder) ListProviderOptionsExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviderOptionsExecute", reflect.TypeOf((*MockDefaultAPI)(nil).ListProviderOptionsExecute), r)
}

// StartCredentialsRotation mocks base method.
func (m *MockDefaultAPI) StartCredentialsRotation(ctx context.Context, projectId, region, clusterName string) v2api.ApiStartCredentialsRotationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCredentialsRotation", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiStartCredentialsRotationRequest)
	return ret0
}

// StartCredentialsRotation indicates an expected call of StartCredentialsRotation.
func (mr *MockDefaultAPIMockRecorder) StartCredentialsRotation(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCredentialsRotation", reflect.TypeOf((*MockDefaultAPI)(nil).StartCredentialsRotation), ctx, projectId, region, clusterName)
}

// StartCredentialsRotationExecute mocks base method.
func (m *MockDefaultAPI) StartCredentialsRotationExecute(r v2api.ApiStartCredentialsRotationRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCredentialsRotationExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCredentialsRotationExecute indicates an expected call of StartCredentialsRotationExecute.
func (mr *MockDefaultAPIMockRecorder) StartCredentialsRotationExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCredentialsRotationExecute", reflect.TypeOf((*MockDefaultAPI)(nil).StartCredentialsRotationExecute), r)
}

// TriggerHibernate mocks base method.
func (m *MockDefaultAPI) TriggerHibernate(ctx context.Context, projectId, region, clusterName string) v2api.ApiTriggerHibernateRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerHibernate", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiTriggerHibernateRequest)
	return ret0
}

// TriggerHibernate indicates an expected call of TriggerHibernate.
func (mr *MockDefaultAPIMockRecorder) TriggerHibernate(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerHibernate", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerHibernate), ctx, projectId, region, clusterName)
}

// TriggerHibernateExecute mocks base method.
func (m *MockDefaultAPI) TriggerHibernateExecute(r v2api.ApiTriggerHibernateRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerHibernateExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerHibernateExecute indicates an expected call of TriggerHibernateExecute.
func (mr *MockDefaultAPIMockRecorder) TriggerHibernateExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerHibernateExecute", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerHibernateExecute), r)
}

// TriggerMaintenance mocks base method.
func (m *MockDefaultAPI) TriggerMaintenance(ctx context.Context, projectId, region, clusterName string) v2api.ApiTriggerMaintenanceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerMaintenance", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiTriggerMaintenanceRequest)
	return ret0
}

// TriggerMaintenance indicates an expected call of TriggerMaintenance.
func (mr *MockDefaultAPIMockRecorder) TriggerMaintenance(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerMaintenance", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerMaintenance), ctx, projectId, region, clusterName)
}

// TriggerMaintenanceExecute mocks base method.
func (m *MockDefaultAPI) TriggerMaintenanceExecute(r v2api.ApiTriggerMaintenanceRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerMaintenanceExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerMaintenanceExecute indicates an expected call of TriggerMaintenanceExecute.
func (mr *MockDefaultAPIMockRecorder) TriggerMaintenanceExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerMaintenanceExecute", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerMaintenanceExecute), r)
}

// TriggerReconcile mocks base method.
func (m *MockDefaultAPI) TriggerReconcile(ctx context.Context, projectId, region, clusterName string) v2api.ApiTriggerReconcileRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerReconcile", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiTriggerReconcileRequest)
	return ret0
}

// TriggerReconcile indicates an expected call of TriggerReconcile.
func (mr *MockDefaultAPIMockRecorder) TriggerReconcile(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerReconcile", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerReconcile), ctx, projectId, region, clusterName)
}

// TriggerReconcileExecute mocks base method.
func (m *MockDefaultAPI) TriggerReconcileExecute(r v2api.ApiTriggerReconcileRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerReconcileExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerReconcileExecute indicates an expected call of TriggerReconcileExecute.
func (mr *MockDefaultAPIMockRecorder) TriggerReconcileExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerReconcileExecute", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerReconcileExecute), r)
}

// TriggerWakeup mocks base method.
func (m *MockDefaultAPI) TriggerWakeup(ctx context.Context, projectId, region, clusterName string) v2api.ApiTriggerWakeupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerWakeup", ctx, projectId, region, clusterName)
	ret0, _ := ret[0].(v2api.ApiTriggerWakeupRequest)
	return ret0
}

// TriggerWakeup indicates an expected call of TriggerWakeup.
func (mr *MockDefaultAPIMockRecorder) TriggerWakeup(ctx, projectId, region, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerWakeup", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerWakeup), ctx, projectId, region, clusterName)
}

// TriggerWakeupExecute mocks base method.
func (m *MockDefaultAPI) TriggerWakeupExecute(r v2api.ApiTriggerWakeupRequest) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerWakeupExecute", r)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerWakeupExecute indicates an expected call of TriggerWakeupExecute.
func (mr *MockDefaultAPIMockRecorder) TriggerWakeupExecute(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerWakeupExecute", reflect.TypeOf((*MockDefaultAPI)(nil).TriggerWakeupExecute), r)
}
