apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: stackit-application-load-balancer-contoller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackit-application-load-balancer-contoller-manager
rules:
  # TODO(jamand): Go through rules again
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingress
  verbs:
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingress/status
  verbs:
  - patch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingressclass
  verbs:
  - list
  - patch
  - update
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackit-application-load-balancer-contoller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackit-application-load-balancer-contoller-manager
subjects:
- kind: ServiceAccount
  name: stackit-application-load-balancer-contoller-manager
  namespace: kube-system
