apiVersion: v1
kind: Service
metadata:
  labels:
    app: stackit-application-load-balancer-contoller-manager
  namespace: kube-system
  name: stackit-application-load-balancer-contoller-manager
spec:
  selector:
    app: stackit-application-load-balancer-contoller-manager
  ports:
  - name: probe
    port: 8081
    targetPort: probe
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  type: ClusterIP
