apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: stackit-application-load-balancer-controller-manager
  annotations:
    cert-manager.io/inject-ca-from: kube-system/stackit-application-load-balancer-controller-manager-webhook-cert
webhooks:
  - name: validate-ingress.stackit.cloud
    rules:
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["ingresses"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: kube-system
        name: stackit-application-load-balancer-controller-manager
        path: "/validate-ingress"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  - name: validate-ingressclass.stackit.cloud
    rules:
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["ingressclasses"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: kube-system
        name: stackit-application-load-balancer-controller-manager
        path: "/validate-ingressclass"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5