changelog:
  exclude:
    labels:
    - no-release-note
  categories:
  - title: ⚠️ Breaking Changes
    labels:
    - breaking
  - title: ✨ Features
    labels:
    - kind/enhancement
  - title: 🐛 Bug Fixes
    labels:
    - kind/bug
  - title: 🚀 Dependency Updates
    labels:
    - kind/upgrade
  - title: ℹ️ Other Changes
    labels:
    - "*"
