// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit/client (interfaces: IaaSClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/iaas_mock.go -typed -package client ./pkg/stackit/client IaaSClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/iaas/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockIaaSClient is a mock of IaaSClient interface.
type MockIaaSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIaaSClientMockRecorder
	isgomock struct{}
}

// MockIaaSClientMockRecorder is the mock recorder for MockIaaSClient.
type MockIaaSClientMockRecorder struct {
	mock *MockIaaSClient
}

// NewMockIaaSClient creates a new mock instance.
func NewMockIaaSClient(ctrl *gomock.Controller) *MockIaaSClient {
	mock := &MockIaaSClient{ctrl: ctrl}
	mock.recorder = &MockIaaSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIaaSClient) EXPECT() *MockIaaSClientMockRecorder {
	return m.recorder
}

// GetServer mocks base method.
func (m *MockIaaSClient) GetServer(ctx context.Context, serverID string) (*v2api.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer", ctx, serverID)
	ret0, _ := ret[0].(*v2api.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServer indicates an expected call of GetServer.
func (mr *MockIaaSClientMockRecorder) GetServer(ctx, serverID any) *MockIaaSClientGetServerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockIaaSClient)(nil).GetServer), ctx, serverID)
	return &MockIaaSClientGetServerCall{Call: call}
}

// MockIaaSClientGetServerCall wrap *gomock.Call
type MockIaaSClientGetServerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIaaSClientGetServerCall) Return(arg0 *v2api.Server, arg1 error) *MockIaaSClientGetServerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIaaSClientGetServerCall) Do(f func(context.Context, string) (*v2api.Server, error)) *MockIaaSClientGetServerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIaaSClientGetServerCall) DoAndReturn(f func(context.Context, string) (*v2api.Server, error)) *MockIaaSClientGetServerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListServers mocks base method.
func (m *MockIaaSClient) ListServers(ctx context.Context) (*[]v2api.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServers", ctx)
	ret0, _ := ret[0].(*[]v2api.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServers indicates an expected call of ListServers.
func (mr *MockIaaSClientMockRecorder) ListServers(ctx any) *MockIaaSClientListServersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServers", reflect.TypeOf((*MockIaaSClient)(nil).ListServers), ctx)
	return &MockIaaSClientListServersCall{Call: call}
}

// MockIaaSClientListServersCall wrap *gomock.Call
type MockIaaSClientListServersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIaaSClientListServersCall) Return(arg0 *[]v2api.Server, arg1 error) *MockIaaSClientListServersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIaaSClientListServersCall) Do(f func(context.Context) (*[]v2api.Server, error)) *MockIaaSClientListServersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIaaSClientListServersCall) DoAndReturn(f func(context.Context) (*[]v2api.Server, error)) *MockIaaSClientListServersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
