// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit/client (interfaces: LoadBalancingClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/loadbalancer_mock.go -package client ./pkg/stackit/client LoadBalancingClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockLoadBalancingClient is a mock of LoadBalancingClient interface.
type MockLoadBalancingClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancingClientMockRecorder
	isgomock struct{}
}

// MockLoadBalancingClientMockRecorder is the mock recorder for MockLoadBalancingClient.
type MockLoadBalancingClientMockRecorder struct {
	mock *MockLoadBalancingClient
}

// NewMockLoadBalancingClient creates a new mock instance.
func NewMockLoadBalancingClient(ctrl *gomock.Controller) *MockLoadBalancingClient {
	mock := &MockLoadBalancingClient{ctrl: ctrl}
	mock.recorder = &MockLoadBalancingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancingClient) EXPECT() *MockLoadBalancingClientMockRecorder {
	return m.recorder
}

// CreateCredentials mocks base method.
func (m *MockLoadBalancingClient) CreateCredentials(ctx context.Context, payload v2api.CreateCredentialsPayload) (*v2api.CreateCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentials", ctx, payload)
	ret0, _ := ret[0].(*v2api.CreateCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredentials indicates an expected call of CreateCredentials.
func (mr *MockLoadBalancingClientMockRecorder) CreateCredentials(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).CreateCredentials), ctx, payload)
}

// CreateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) CreateLoadBalancer(ctx context.Context, payload v2api.CreateLoadBalancerPayload) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, payload)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) CreateLoadBalancer(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).CreateLoadBalancer), ctx, payload)
}

// DeleteCredentials mocks base method.
func (m *MockLoadBalancingClient) DeleteCredentials(ctx context.Context, credentialsRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentials", ctx, credentialsRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredentials indicates an expected call of DeleteCredentials.
func (mr *MockLoadBalancingClientMockRecorder) DeleteCredentials(ctx, credentialsRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteCredentials), ctx, credentialsRef)
}

// DeleteLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) DeleteLoadBalancer(ctx context.Context, lbName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, lbName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) DeleteLoadBalancer(ctx, lbName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteLoadBalancer), ctx, lbName)
}

// GetCredentials mocks base method.
func (m *MockLoadBalancingClient) GetCredentials(ctx context.Context, credentialsRef string) (*v2api.GetCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, credentialsRef)
	ret0, _ := ret[0].(*v2api.GetCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockLoadBalancingClientMockRecorder) GetCredentials(ctx, credentialsRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetCredentials), ctx, credentialsRef)
}

// GetLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) GetLoadBalancer(ctx context.Context, id string) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, id)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) GetLoadBalancer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetLoadBalancer), ctx, id)
}

// ListCredentials mocks base method.
func (m *MockLoadBalancingClient) ListCredentials(ctx context.Context) (*v2api.ListCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx)
	ret0, _ := ret[0].(*v2api.ListCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockLoadBalancingClientMockRecorder) ListCredentials(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListCredentials), ctx)
}

// ListLoadBalancers mocks base method.
func (m *MockLoadBalancingClient) ListLoadBalancers(ctx context.Context) ([]v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancers", ctx)
	ret0, _ := ret[0].([]v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancers indicates an expected call of ListLoadBalancers.
func (mr *MockLoadBalancingClientMockRecorder) ListLoadBalancers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancers", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListLoadBalancers), ctx)
}

// UpdateCredentials mocks base method.
func (m *MockLoadBalancingClient) UpdateCredentials(ctx context.Context, credentialsRef string, payload v2api.UpdateCredentialsPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentials", ctx, credentialsRef, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredentials indicates an expected call of UpdateCredentials.
func (mr *MockLoadBalancingClientMockRecorder) UpdateCredentials(ctx, credentialsRef, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateCredentials), ctx, credentialsRef, payload)
}

// UpdateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) UpdateLoadBalancer(ctx context.Context, lbName string, updates v2api.UpdateLoadBalancerPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancer", ctx, lbName, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoadBalancer indicates an expected call of UpdateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) UpdateLoadBalancer(ctx, lbName, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateLoadBalancer), ctx, lbName, updates)
}

// UpdateTargetPool mocks base method.
func (m *MockLoadBalancingClient) UpdateTargetPool(ctx context.Context, name, targetPoolName string, payload v2api.UpdateTargetPoolPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTargetPool", ctx, name, targetPoolName, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTargetPool indicates an expected call of UpdateTargetPool.
func (mr *MockLoadBalancingClientMockRecorder) UpdateTargetPool(ctx, name, targetPoolName, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTargetPool", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateTargetPool), ctx, name, targetPoolName, payload)
}
