// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit/client (interfaces: LoadBalancingClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/loadbalancer_mock.go -typed -package client ./pkg/stackit/client LoadBalancingClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/loadbalancer/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockLoadBalancingClient is a mock of LoadBalancingClient interface.
type MockLoadBalancingClient struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancingClientMockRecorder
	isgomock struct{}
}

// MockLoadBalancingClientMockRecorder is the mock recorder for MockLoadBalancingClient.
type MockLoadBalancingClientMockRecorder struct {
	mock *MockLoadBalancingClient
}

// NewMockLoadBalancingClient creates a new mock instance.
func NewMockLoadBalancingClient(ctrl *gomock.Controller) *MockLoadBalancingClient {
	mock := &MockLoadBalancingClient{ctrl: ctrl}
	mock.recorder = &MockLoadBalancingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancingClient) EXPECT() *MockLoadBalancingClientMockRecorder {
	return m.recorder
}

// CreateCredentials mocks base method.
func (m *MockLoadBalancingClient) CreateCredentials(ctx context.Context, payload v2api.CreateCredentialsPayload) (*v2api.CreateCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredentials", ctx, payload)
	ret0, _ := ret[0].(*v2api.CreateCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredentials indicates an expected call of CreateCredentials.
func (mr *MockLoadBalancingClientMockRecorder) CreateCredentials(ctx, payload any) *MockLoadBalancingClientCreateCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).CreateCredentials), ctx, payload)
	return &MockLoadBalancingClientCreateCredentialsCall{Call: call}
}

// MockLoadBalancingClientCreateCredentialsCall wrap *gomock.Call
type MockLoadBalancingClientCreateCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientCreateCredentialsCall) Return(arg0 *v2api.CreateCredentialsResponse, arg1 error) *MockLoadBalancingClientCreateCredentialsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientCreateCredentialsCall) Do(f func(context.Context, v2api.CreateCredentialsPayload) (*v2api.CreateCredentialsResponse, error)) *MockLoadBalancingClientCreateCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientCreateCredentialsCall) DoAndReturn(f func(context.Context, v2api.CreateCredentialsPayload) (*v2api.CreateCredentialsResponse, error)) *MockLoadBalancingClientCreateCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) CreateLoadBalancer(ctx context.Context, payload *v2api.CreateLoadBalancerPayload) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, payload)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) CreateLoadBalancer(ctx, payload any) *MockLoadBalancingClientCreateLoadBalancerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).CreateLoadBalancer), ctx, payload)
	return &MockLoadBalancingClientCreateLoadBalancerCall{Call: call}
}

// MockLoadBalancingClientCreateLoadBalancerCall wrap *gomock.Call
type MockLoadBalancingClientCreateLoadBalancerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientCreateLoadBalancerCall) Return(arg0 *v2api.LoadBalancer, arg1 error) *MockLoadBalancingClientCreateLoadBalancerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientCreateLoadBalancerCall) Do(f func(context.Context, *v2api.CreateLoadBalancerPayload) (*v2api.LoadBalancer, error)) *MockLoadBalancingClientCreateLoadBalancerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientCreateLoadBalancerCall) DoAndReturn(f func(context.Context, *v2api.CreateLoadBalancerPayload) (*v2api.LoadBalancer, error)) *MockLoadBalancingClientCreateLoadBalancerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCredentials mocks base method.
func (m *MockLoadBalancingClient) DeleteCredentials(ctx context.Context, credentialsRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredentials", ctx, credentialsRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredentials indicates an expected call of DeleteCredentials.
func (mr *MockLoadBalancingClientMockRecorder) DeleteCredentials(ctx, credentialsRef any) *MockLoadBalancingClientDeleteCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteCredentials), ctx, credentialsRef)
	return &MockLoadBalancingClientDeleteCredentialsCall{Call: call}
}

// MockLoadBalancingClientDeleteCredentialsCall wrap *gomock.Call
type MockLoadBalancingClientDeleteCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientDeleteCredentialsCall) Return(arg0 error) *MockLoadBalancingClientDeleteCredentialsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientDeleteCredentialsCall) Do(f func(context.Context, string) error) *MockLoadBalancingClientDeleteCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientDeleteCredentialsCall) DoAndReturn(f func(context.Context, string) error) *MockLoadBalancingClientDeleteCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) DeleteLoadBalancer(ctx context.Context, lbName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, lbName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) DeleteLoadBalancer(ctx, lbName any) *MockLoadBalancingClientDeleteLoadBalancerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).DeleteLoadBalancer), ctx, lbName)
	return &MockLoadBalancingClientDeleteLoadBalancerCall{Call: call}
}

// MockLoadBalancingClientDeleteLoadBalancerCall wrap *gomock.Call
type MockLoadBalancingClientDeleteLoadBalancerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientDeleteLoadBalancerCall) Return(arg0 error) *MockLoadBalancingClientDeleteLoadBalancerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientDeleteLoadBalancerCall) Do(f func(context.Context, string) error) *MockLoadBalancingClientDeleteLoadBalancerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientDeleteLoadBalancerCall) DoAndReturn(f func(context.Context, string) error) *MockLoadBalancingClientDeleteLoadBalancerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCredentials mocks base method.
func (m *MockLoadBalancingClient) GetCredentials(ctx context.Context, credentialsRef string) (*v2api.GetCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, credentialsRef)
	ret0, _ := ret[0].(*v2api.GetCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockLoadBalancingClientMockRecorder) GetCredentials(ctx, credentialsRef any) *MockLoadBalancingClientGetCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetCredentials), ctx, credentialsRef)
	return &MockLoadBalancingClientGetCredentialsCall{Call: call}
}

// MockLoadBalancingClientGetCredentialsCall wrap *gomock.Call
type MockLoadBalancingClientGetCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientGetCredentialsCall) Return(arg0 *v2api.GetCredentialsResponse, arg1 error) *MockLoadBalancingClientGetCredentialsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientGetCredentialsCall) Do(f func(context.Context, string) (*v2api.GetCredentialsResponse, error)) *MockLoadBalancingClientGetCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientGetCredentialsCall) DoAndReturn(f func(context.Context, string) (*v2api.GetCredentialsResponse, error)) *MockLoadBalancingClientGetCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) GetLoadBalancer(ctx context.Context, id string) (*v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, id)
	ret0, _ := ret[0].(*v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) GetLoadBalancer(ctx, id any) *MockLoadBalancingClientGetLoadBalancerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).GetLoadBalancer), ctx, id)
	return &MockLoadBalancingClientGetLoadBalancerCall{Call: call}
}

// MockLoadBalancingClientGetLoadBalancerCall wrap *gomock.Call
type MockLoadBalancingClientGetLoadBalancerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientGetLoadBalancerCall) Return(arg0 *v2api.LoadBalancer, arg1 error) *MockLoadBalancingClientGetLoadBalancerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientGetLoadBalancerCall) Do(f func(context.Context, string) (*v2api.LoadBalancer, error)) *MockLoadBalancingClientGetLoadBalancerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientGetLoadBalancerCall) DoAndReturn(f func(context.Context, string) (*v2api.LoadBalancer, error)) *MockLoadBalancingClientGetLoadBalancerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListCredentials mocks base method.
func (m *MockLoadBalancingClient) ListCredentials(ctx context.Context) (*v2api.ListCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentials", ctx)
	ret0, _ := ret[0].(*v2api.ListCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentials indicates an expected call of ListCredentials.
func (mr *MockLoadBalancingClientMockRecorder) ListCredentials(ctx any) *MockLoadBalancingClientListCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListCredentials), ctx)
	return &MockLoadBalancingClientListCredentialsCall{Call: call}
}

// MockLoadBalancingClientListCredentialsCall wrap *gomock.Call
type MockLoadBalancingClientListCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientListCredentialsCall) Return(arg0 *v2api.ListCredentialsResponse, arg1 error) *MockLoadBalancingClientListCredentialsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientListCredentialsCall) Do(f func(context.Context) (*v2api.ListCredentialsResponse, error)) *MockLoadBalancingClientListCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientListCredentialsCall) DoAndReturn(f func(context.Context) (*v2api.ListCredentialsResponse, error)) *MockLoadBalancingClientListCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLoadBalancers mocks base method.
func (m *MockLoadBalancingClient) ListLoadBalancers(ctx context.Context) ([]v2api.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancers", ctx)
	ret0, _ := ret[0].([]v2api.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancers indicates an expected call of ListLoadBalancers.
func (mr *MockLoadBalancingClientMockRecorder) ListLoadBalancers(ctx any) *MockLoadBalancingClientListLoadBalancersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancers", reflect.TypeOf((*MockLoadBalancingClient)(nil).ListLoadBalancers), ctx)
	return &MockLoadBalancingClientListLoadBalancersCall{Call: call}
}

// MockLoadBalancingClientListLoadBalancersCall wrap *gomock.Call
type MockLoadBalancingClientListLoadBalancersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientListLoadBalancersCall) Return(arg0 []v2api.LoadBalancer, arg1 error) *MockLoadBalancingClientListLoadBalancersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientListLoadBalancersCall) Do(f func(context.Context) ([]v2api.LoadBalancer, error)) *MockLoadBalancingClientListLoadBalancersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientListLoadBalancersCall) DoAndReturn(f func(context.Context) ([]v2api.LoadBalancer, error)) *MockLoadBalancingClientListLoadBalancersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCredentials mocks base method.
func (m *MockLoadBalancingClient) UpdateCredentials(ctx context.Context, credentialsRef string, payload v2api.UpdateCredentialsPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentials", ctx, credentialsRef, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredentials indicates an expected call of UpdateCredentials.
func (mr *MockLoadBalancingClientMockRecorder) UpdateCredentials(ctx, credentialsRef, payload any) *MockLoadBalancingClientUpdateCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentials", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateCredentials), ctx, credentialsRef, payload)
	return &MockLoadBalancingClientUpdateCredentialsCall{Call: call}
}

// MockLoadBalancingClientUpdateCredentialsCall wrap *gomock.Call
type MockLoadBalancingClientUpdateCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientUpdateCredentialsCall) Return(arg0 error) *MockLoadBalancingClientUpdateCredentialsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientUpdateCredentialsCall) Do(f func(context.Context, string, v2api.UpdateCredentialsPayload) error) *MockLoadBalancingClientUpdateCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientUpdateCredentialsCall) DoAndReturn(f func(context.Context, string, v2api.UpdateCredentialsPayload) error) *MockLoadBalancingClientUpdateCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateLoadBalancer mocks base method.
func (m *MockLoadBalancingClient) UpdateLoadBalancer(ctx context.Context, lbName string, updates *v2api.UpdateLoadBalancerPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoadBalancer", ctx, lbName, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoadBalancer indicates an expected call of UpdateLoadBalancer.
func (mr *MockLoadBalancingClientMockRecorder) UpdateLoadBalancer(ctx, lbName, updates any) *MockLoadBalancingClientUpdateLoadBalancerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoadBalancer", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateLoadBalancer), ctx, lbName, updates)
	return &MockLoadBalancingClientUpdateLoadBalancerCall{Call: call}
}

// MockLoadBalancingClientUpdateLoadBalancerCall wrap *gomock.Call
type MockLoadBalancingClientUpdateLoadBalancerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientUpdateLoadBalancerCall) Return(arg0 error) *MockLoadBalancingClientUpdateLoadBalancerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientUpdateLoadBalancerCall) Do(f func(context.Context, string, *v2api.UpdateLoadBalancerPayload) error) *MockLoadBalancingClientUpdateLoadBalancerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientUpdateLoadBalancerCall) DoAndReturn(f func(context.Context, string, *v2api.UpdateLoadBalancerPayload) error) *MockLoadBalancingClientUpdateLoadBalancerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTargetPool mocks base method.
func (m *MockLoadBalancingClient) UpdateTargetPool(ctx context.Context, name, targetPoolName string, payload v2api.UpdateTargetPoolPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTargetPool", ctx, name, targetPoolName, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTargetPool indicates an expected call of UpdateTargetPool.
func (mr *MockLoadBalancingClientMockRecorder) UpdateTargetPool(ctx, name, targetPoolName, payload any) *MockLoadBalancingClientUpdateTargetPoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTargetPool", reflect.TypeOf((*MockLoadBalancingClient)(nil).UpdateTargetPool), ctx, name, targetPoolName, payload)
	return &MockLoadBalancingClientUpdateTargetPoolCall{Call: call}
}

// MockLoadBalancingClientUpdateTargetPoolCall wrap *gomock.Call
type MockLoadBalancingClientUpdateTargetPoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoadBalancingClientUpdateTargetPoolCall) Return(arg0 error) *MockLoadBalancingClientUpdateTargetPoolCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoadBalancingClientUpdateTargetPoolCall) Do(f func(context.Context, string, string, v2api.UpdateTargetPoolPayload) error) *MockLoadBalancingClientUpdateTargetPoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoadBalancingClientUpdateTargetPoolCall) DoAndReturn(f func(context.Context, string, string, v2api.UpdateTargetPoolPayload) error) *MockLoadBalancingClientUpdateTargetPoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
