// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit/client (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/mock.go -package client ./pkg/stackit/client Factory
//

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	client "github.com/stackitcloud/cloud-provider-stackit/pkg/stackit/client"
	config "github.com/stackitcloud/stackit-sdk-go/core/config"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// IaaS mocks base method.
func (m *MockFactory) IaaS(options []config.ConfigurationOption) (client.IaaSClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IaaS", options)
	ret0, _ := ret[0].(client.IaaSClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IaaS indicates an expected call of IaaS.
func (mr *MockFactoryMockRecorder) IaaS(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IaaS", reflect.TypeOf((*MockFactory)(nil).IaaS), options)
}

// LoadBalancing mocks base method.
func (m *MockFactory) LoadBalancing(options []config.ConfigurationOption) (client.LoadBalancingClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancing", options)
	ret0, _ := ret[0].(client.LoadBalancingClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBalancing indicates an expected call of LoadBalancing.
func (mr *MockFactoryMockRecorder) LoadBalancing(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancing", reflect.TypeOf((*MockFactory)(nil).LoadBalancing), options)
}
