// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit/client (interfaces: SKEClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/client/mock/ske_mock.go -typed -package client ./pkg/stackit/client SKEClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/ske/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockSKEClient is a mock of SKEClient interface.
type MockSKEClient struct {
	ctrl     *gomock.Controller
	recorder *MockSKEClientMockRecorder
	isgomock struct{}
}

// MockSKEClientMockRecorder is the mock recorder for MockSKEClient.
type MockSKEClientMockRecorder struct {
	mock *MockSKEClient
}

// NewMockSKEClient creates a new mock instance.
func NewMockSKEClient(ctrl *gomock.Controller) *MockSKEClient {
	mock := &MockSKEClient{ctrl: ctrl}
	mock.recorder = &MockSKEClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSKEClient) EXPECT() *MockSKEClientMockRecorder {
	return m.recorder
}

// CreateKubeconfig mocks base method.
func (m *MockSKEClient) CreateKubeconfig(ctx context.Context, clusterName string, payload v2api.CreateKubeconfigPayload) (*v2api.Kubeconfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubeconfig", ctx, clusterName, payload)
	ret0, _ := ret[0].(*v2api.Kubeconfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKubeconfig indicates an expected call of CreateKubeconfig.
func (mr *MockSKEClientMockRecorder) CreateKubeconfig(ctx, clusterName, payload any) *MockSKEClientCreateKubeconfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubeconfig", reflect.TypeOf((*MockSKEClient)(nil).CreateKubeconfig), ctx, clusterName, payload)
	return &MockSKEClientCreateKubeconfigCall{Call: call}
}

// MockSKEClientCreateKubeconfigCall wrap *gomock.Call
type MockSKEClientCreateKubeconfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientCreateKubeconfigCall) Return(arg0 *v2api.Kubeconfig, arg1 error) *MockSKEClientCreateKubeconfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientCreateKubeconfigCall) Do(f func(context.Context, string, v2api.CreateKubeconfigPayload) (*v2api.Kubeconfig, error)) *MockSKEClientCreateKubeconfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientCreateKubeconfigCall) DoAndReturn(f func(context.Context, string, v2api.CreateKubeconfigPayload) (*v2api.Kubeconfig, error)) *MockSKEClientCreateKubeconfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateOrUpdateCluster mocks base method.
func (m *MockSKEClient) CreateOrUpdateCluster(ctx context.Context, clusterName string, payload v2api.CreateOrUpdateClusterPayload) (*v2api.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateCluster", ctx, clusterName, payload)
	ret0, _ := ret[0].(*v2api.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateCluster indicates an expected call of CreateOrUpdateCluster.
func (mr *MockSKEClientMockRecorder) CreateOrUpdateCluster(ctx, clusterName, payload any) *MockSKEClientCreateOrUpdateClusterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateCluster", reflect.TypeOf((*MockSKEClient)(nil).CreateOrUpdateCluster), ctx, clusterName, payload)
	return &MockSKEClientCreateOrUpdateClusterCall{Call: call}
}

// MockSKEClientCreateOrUpdateClusterCall wrap *gomock.Call
type MockSKEClientCreateOrUpdateClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientCreateOrUpdateClusterCall) Return(arg0 *v2api.Cluster, arg1 error) *MockSKEClientCreateOrUpdateClusterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientCreateOrUpdateClusterCall) Do(f func(context.Context, string, v2api.CreateOrUpdateClusterPayload) (*v2api.Cluster, error)) *MockSKEClientCreateOrUpdateClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientCreateOrUpdateClusterCall) DoAndReturn(f func(context.Context, string, v2api.CreateOrUpdateClusterPayload) (*v2api.Cluster, error)) *MockSKEClientCreateOrUpdateClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCluster mocks base method.
func (m *MockSKEClient) DeleteCluster(ctx context.Context, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockSKEClientMockRecorder) DeleteCluster(ctx, clusterName any) *MockSKEClientDeleteClusterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockSKEClient)(nil).DeleteCluster), ctx, clusterName)
	return &MockSKEClientDeleteClusterCall{Call: call}
}

// MockSKEClientDeleteClusterCall wrap *gomock.Call
type MockSKEClientDeleteClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientDeleteClusterCall) Return(arg0 error) *MockSKEClientDeleteClusterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientDeleteClusterCall) Do(f func(context.Context, string) error) *MockSKEClientDeleteClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientDeleteClusterCall) DoAndReturn(f func(context.Context, string) error) *MockSKEClientDeleteClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCluster mocks base method.
func (m *MockSKEClient) GetCluster(ctx context.Context, clusterName string) (*v2api.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, clusterName)
	ret0, _ := ret[0].(*v2api.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockSKEClientMockRecorder) GetCluster(ctx, clusterName any) *MockSKEClientGetClusterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockSKEClient)(nil).GetCluster), ctx, clusterName)
	return &MockSKEClientGetClusterCall{Call: call}
}

// MockSKEClientGetClusterCall wrap *gomock.Call
type MockSKEClientGetClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientGetClusterCall) Return(arg0 *v2api.Cluster, arg1 error) *MockSKEClientGetClusterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientGetClusterCall) Do(f func(context.Context, string) (*v2api.Cluster, error)) *MockSKEClientGetClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientGetClusterCall) DoAndReturn(f func(context.Context, string) (*v2api.Cluster, error)) *MockSKEClientGetClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProviderOptions mocks base method.
func (m *MockSKEClient) ListProviderOptions(ctx context.Context) (*v2api.ProviderOptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviderOptions", ctx)
	ret0, _ := ret[0].(*v2api.ProviderOptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviderOptions indicates an expected call of ListProviderOptions.
func (mr *MockSKEClientMockRecorder) ListProviderOptions(ctx any) *MockSKEClientListProviderOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviderOptions", reflect.TypeOf((*MockSKEClient)(nil).ListProviderOptions), ctx)
	return &MockSKEClientListProviderOptionsCall{Call: call}
}

// MockSKEClientListProviderOptionsCall wrap *gomock.Call
type MockSKEClientListProviderOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientListProviderOptionsCall) Return(arg0 *v2api.ProviderOptions, arg1 error) *MockSKEClientListProviderOptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientListProviderOptionsCall) Do(f func(context.Context) (*v2api.ProviderOptions, error)) *MockSKEClientListProviderOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientListProviderOptionsCall) DoAndReturn(f func(context.Context) (*v2api.ProviderOptions, error)) *MockSKEClientListProviderOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WaitClusterDeleted mocks base method.
func (m *MockSKEClient) WaitClusterDeleted(ctx context.Context, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitClusterDeleted", ctx, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitClusterDeleted indicates an expected call of WaitClusterDeleted.
func (mr *MockSKEClientMockRecorder) WaitClusterDeleted(ctx, clusterName any) *MockSKEClientWaitClusterDeletedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitClusterDeleted", reflect.TypeOf((*MockSKEClient)(nil).WaitClusterDeleted), ctx, clusterName)
	return &MockSKEClientWaitClusterDeletedCall{Call: call}
}

// MockSKEClientWaitClusterDeletedCall wrap *gomock.Call
type MockSKEClientWaitClusterDeletedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientWaitClusterDeletedCall) Return(arg0 error) *MockSKEClientWaitClusterDeletedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientWaitClusterDeletedCall) Do(f func(context.Context, string) error) *MockSKEClientWaitClusterDeletedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientWaitClusterDeletedCall) DoAndReturn(f func(context.Context, string) error) *MockSKEClientWaitClusterDeletedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WaitClusterReady mocks base method.
func (m *MockSKEClient) WaitClusterReady(ctx context.Context, clusterName string) (*v2api.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitClusterReady", ctx, clusterName)
	ret0, _ := ret[0].(*v2api.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitClusterReady indicates an expected call of WaitClusterReady.
func (mr *MockSKEClientMockRecorder) WaitClusterReady(ctx, clusterName any) *MockSKEClientWaitClusterReadyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitClusterReady", reflect.TypeOf((*MockSKEClient)(nil).WaitClusterReady), ctx, clusterName)
	return &MockSKEClientWaitClusterReadyCall{Call: call}
}

// MockSKEClientWaitClusterReadyCall wrap *gomock.Call
type MockSKEClientWaitClusterReadyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSKEClientWaitClusterReadyCall) Return(arg0 *v2api.Cluster, arg1 error) *MockSKEClientWaitClusterReadyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSKEClientWaitClusterReadyCall) Do(f func(context.Context, string) (*v2api.Cluster, error)) *MockSKEClientWaitClusterReadyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSKEClientWaitClusterReadyCall) DoAndReturn(f func(context.Context, string) (*v2api.Cluster, error)) *MockSKEClientWaitClusterReadyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
