apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: cloud-provider-stackit
  labels:
    app: cloud-provider-stackit
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cloud-provider-stackit
  template:
    metadata:
      labels:
        app: cloud-provider-stackit
    spec:
      serviceAccountName: cloud-provider-stackit
      terminationGracePeriodSeconds: 30
      containers:
      - name: cloud-provider-stackit
        image: registry.ske.stackit.cloud/stackitcloud/cloud-provider-stackit/cloud-provider-stackit:latest
        args:
        - --allow-untagged-cloud
        - --cloud-provider=stackit
        - --route-reconciliation-period=30s
        - --webhook-secure-port=0
        - --leader-elect=true
        - --leader-elect-resource-name=stackit-cloud-controller-manager # Must not collide with the lease for OpenStack's cloud controller manager.
        - --concurrent-service-syncs=3
        - --controllers=service-lb-controller
        - --authorization-always-allow-paths=/metrics
        # - --cloud-config=cloud-config.yaml
        # - --cluster-name=<cluster-id>
        ports:
        - containerPort: 10258
          hostPort: 10258
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
          requests:
            cpu: "0.1"
            memory: 100Mi
