apiVersion: v1
kind: Service
metadata:
  labels:
    app: stackit-cloud-controller-manager
  namespace: kube-system
  name: stackit-cloud-controller-manager
spec:
  selector:
    app: stackit-cloud-controller-manager
  ports:
  - name: https
    port: 10258
    targetPort: https
    protocol: TCP
  type: ClusterIP
