apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../csi-plugin

patches:
- path: driver-name-patch.yaml
- target:
    group: storage.k8s.io
    version: v1
    kind: CSIDriver
    name: block-storage.csi.stackit.cloud
  patch: |-
    - op: replace
      path: /metadata/name
      value: kubetest2.csi.stackit.cloud
