apiVersion: v1
kind: Service
metadata:
  labels:
    app: stackit-cloud-controller-manager
  namespace: kube-system
  name: stackit-cloud-controller-manager
spec:
  selector:
    app: stackit-cloud-controller-manager
  ports:
  - name: main
    port: 80
    targetPort: 8888
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  type: ClusterIP
