apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: stackit-credential-provider
    matchImages:
      - "registry.onstackit.cloud"
    env:
      - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
        value: /stackit/key.json
    defaultCacheDuration: "1h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1
