apiVersion: v1
kind: Service
metadata:
  name: demo-with-a-very-long-long-name
  annotations:
    lb.stackit.cloud/external-address: 45.135.245.121
    # lb.stackit.cloud/internal-lb: "true"
    yawol.stackit.cloud/className: stackit
    # yawol.stackit.cloud/className: stackit.cloud/yawol
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: http-alt
      port: 8080
      targetPort: 80
  type: LoadBalancer
