apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: block-storage.csi.stackit.cloud
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
