# This YAML file contains driver-registrar & csi driver nodeplugin API objects,
# which are necessary to run csi nodeplugin for stackit blockstorage.

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-stackit-nodeplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-stackit-nodeplugin
  template:
    metadata:
      labels:
        app: csi-stackit-nodeplugin
    spec:
      tolerations:
      - operator: Exists
      serviceAccount: csi-stackit-node-sa
      hostNetwork: true
      containers:
      - name: node-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
        args:
        - "--csi-address=$(ADDRESS)"
        - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/block-storage.csi.stackit.cloud/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: liveness-probe
        image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0
        args:
        - --csi-address=/csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: stackit-csi-plugin
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: ghcr.io/stackitcloud/cloud-provider-stackit/stackit-csi-plugin:release-v1.33
        args:
        - /bin/stackit-csi-plugin
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--provide-controller-service=false"
        - "--cloud-config=$(CLOUD_CONFIG)"
        - "--v=1"
        env:
        - name: CSI_ENDPOINT
          value: unix://csi/csi.sock
        - name: CLOUD_CONFIG
          value: /etc/config/cloud.conf
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
        - name: pods-probe-dir
          mountPath: /dev
          mountPropagation: "HostToContainer"
        - name: cloud-config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/block-storage.csi.stackit.cloud
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: pods-probe-dir
        hostPath:
          path: /dev
          type: Directory
      - name: cloud-config
        configMap:
          name: stackit-cloud-config
