// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/stackit (interfaces: CertificatesClient)
//
// Generated by this command:
//
//	mockgen -destination ./pkg/stackit/applicationloadbalancercertificates_mock.go -package stackit ./pkg/stackit CertificatesClient
//

// Package stackit is a generated GoMock package.
package stackit

import (
	context "context"
	reflect "reflect"

	v2api "github.com/stackitcloud/stackit-sdk-go/services/certificates/v2api"
	gomock "go.uber.org/mock/gomock"
)

// MockCertificatesClient is a mock of CertificatesClient interface.
type MockCertificatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockCertificatesClientMockRecorder
	isgomock struct{}
}

// MockCertificatesClientMockRecorder is the mock recorder for MockCertificatesClient.
type MockCertificatesClientMockRecorder struct {
	mock *MockCertificatesClient
}

// NewMockCertificatesClient creates a new mock instance.
func NewMockCertificatesClient(ctrl *gomock.Controller) *MockCertificatesClient {
	mock := &MockCertificatesClient{ctrl: ctrl}
	mock.recorder = &MockCertificatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificatesClient) EXPECT() *MockCertificatesClientMockRecorder {
	return m.recorder
}

// CreateCertificate mocks base method.
func (m *MockCertificatesClient) CreateCertificate(ctx context.Context, projectID, region string, certificate *v2api.CreateCertificatePayload) (*v2api.GetCertificateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCertificate", ctx, projectID, region, certificate)
	ret0, _ := ret[0].(*v2api.GetCertificateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCertificate indicates an expected call of CreateCertificate.
func (mr *MockCertificatesClientMockRecorder) CreateCertificate(ctx, projectID, region, certificate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCertificate", reflect.TypeOf((*MockCertificatesClient)(nil).CreateCertificate), ctx, projectID, region, certificate)
}

// DeleteCertificate mocks base method.
func (m *MockCertificatesClient) DeleteCertificate(ctx context.Context, projectID, region, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCertificate", ctx, projectID, region, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCertificate indicates an expected call of DeleteCertificate.
func (mr *MockCertificatesClientMockRecorder) DeleteCertificate(ctx, projectID, region, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCertificate", reflect.TypeOf((*MockCertificatesClient)(nil).DeleteCertificate), ctx, projectID, region, name)
}

// GetCertificate mocks base method.
func (m *MockCertificatesClient) GetCertificate(ctx context.Context, projectID, region, name string) (*v2api.GetCertificateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificate", ctx, projectID, region, name)
	ret0, _ := ret[0].(*v2api.GetCertificateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificate indicates an expected call of GetCertificate.
func (mr *MockCertificatesClientMockRecorder) GetCertificate(ctx, projectID, region, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificate", reflect.TypeOf((*MockCertificatesClient)(nil).GetCertificate), ctx, projectID, region, name)
}

// ListCertificate mocks base method.
func (m *MockCertificatesClient) ListCertificate(ctx context.Context, projectID, region string) (*v2api.ListCertificatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCertificate", ctx, projectID, region)
	ret0, _ := ret[0].(*v2api.ListCertificatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCertificate indicates an expected call of ListCertificate.
func (mr *MockCertificatesClientMockRecorder) ListCertificate(ctx, projectID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCertificate", reflect.TypeOf((*MockCertificatesClient)(nil).ListCertificate), ctx, projectID, region)
}
